# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20191124_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Gform'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('multiline', 'Multi Line Text'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('dropdown', 'Dropdown'), ('radio', 'Radio Buttons'), ('file_upload', 'Upload File')], default='multiline', max_length=50),
        ),
    ]
