# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-24 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20191124_0626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=2000)),
                ('gform', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Gform')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='gform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Gform'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('multiline', 'Multi Line Text'), ('singleline', 'Single line Text'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('file_upload', 'Upload File'), ('email', 'E-mail')], default='multiline', max_length=50),
        ),
    ]
