# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 00:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20191124_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Gform'),
        ),
        migrations.AlterField(
            model_name='question',
            name='ques_type',
            field=models.CharField(choices=[('multiline', 'Multi Line Text'), ('singleline', 'Single line Text'), ('number', 'Number'), ('num_range', 'Numeric Range'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('radio', 'Radio Buttons'), ('file_upload', 'Upload File'), ('email', 'E-mail')], default='multiline', max_length=50),
        ),
        migrations.AlterField(
            model_name='response',
            name='gform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='music.Gform'),
        ),
    ]
