# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-06 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer1', models.CharField(max_length=100)),
                ('Answer2', models.CharField(max_length=100)),
                ('Answer3', models.CharField(max_length=200)),
            ],
        ),
    ]
