# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-06 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='user1',
            field=models.CharField(default='Hi', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Answer2',
            field=models.CharField(max_length=200),
        ),
    ]
