# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-06 21:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191106_1929'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data2',
        ),
    ]
