# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-07 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_data2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default='Hi', max_length=100)),
                ('Answer1', models.CharField(default='Hi', max_length=100)),
                ('Answer2', models.CharField(default='Hi', max_length=200)),
                ('Answer3', models.CharField(default='Hi', max_length=200)),
            ],
        ),
    ]
