# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-22 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_data2'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TypeID', models.IntegerField()),
                ('Type', models.CharField(default='Hi', max_length=50)),
            ],
        ),
    ]
