# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-22 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_questype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QuestionID', models.IntegerField()),
                ('FormID', models.IntegerField()),
                ('TypeID', models.IntegerField()),
                ('Questxt', models.CharField(default='Hi', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserID', models.IntegerField()),
                ('FormID', models.IntegerField()),
            ],
        ),
    ]
