# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-11-22 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_question_userform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Options', models.CharField(default='Hi', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='question',
            old_name='QuestionID',
            new_name='QuesID',
        ),
        migrations.AlterField(
            model_name='question',
            name='FormID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserForm'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('QuesID', 'FormID')]),
        ),
        migrations.AlterUniqueTogether(
            name='userform',
            unique_together=set([('UserID', 'FormID')]),
        ),
        migrations.AddField(
            model_name='mcq',
            name='QuesID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
